import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';

/*
* in this part we add the file name (must be the same file name.g.dart) of TypeAdapter which will be
* automatically generated by writing [flutter packages pub run build_runner build]
* in the terminal
* */
part 'note_model.g.dart';

/*
* here we add a unique id of the model
* */
@HiveType(typeId: 0)
class NoteModel extends HiveObject {
  /*
  * here we add a unique id of each field
  * */
  @HiveField(0)
  String title;
  @HiveField(1)
  String content;
  @HiveField(2)
  final String date;
  @HiveField(3)
  int color;
  @HiveField(4)
  String id;

  NoteModel({
    required this.title,
    required this.content,
    required this.date,
    required this.color,
  }) : id = const Uuid().v4();
}
